# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# azure-pipelines-frontend.yml
# This pipeline builds and deploys the React frontend to Azure Static Web Apps

# azure-pipelines-frontend.yml

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  staticWebAppName: 'myedusync'
  # Make sure `myvariable` is added securely from Azure DevOps Pipeline UI (as a secret variable)
  myvariable: $(newvariable)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build React App'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'              # Path to your React app source code
      output_location: 'build'       # NOT 'dist' for Create React App; use 'dist' only for Vite
      azure_static_web_apps_api_token: $(myvariable)
    displayName: 'Deploy to Azure Static Web Apps'

  # Optional: Publish artifacts if needed
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
